// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwleuewbsgfrkvaiqzmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3bGV1ZXdic2dmcmt2YWlxem12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDAwNTcsImV4cCI6MjA2OTUxNjA1N30.S_0CrwBOOICTz4DkiQcpIWN9QHBqjeCpsyPqfPPxkxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});